/**
 * 0nMCP Detailed Tool Catalog — Per-service tool listings
 * Generated from 0nMCP v1.7.0 source
 */

export interface Tool {
  name: string
  description: string
  type: "tool" | "action" | "trigger"
}

export interface ServiceTools {
  serviceId: string
  tools: Tool[]
}

// CRM Module — 245 tools across 12 sub-modules
const CRM_TOOLS: Tool[] = [
  // Auth (5)
  { name: "crm_get_access_token", description: "Exchange auth code for access token", type: "tool" },
  { name: "crm_refresh_token", description: "Refresh an expired access token", type: "tool" },
  { name: "crm_get_token_info", description: "Get token metadata and scopes", type: "tool" },
  { name: "crm_revoke_token", description: "Revoke an access token", type: "tool" },
  { name: "crm_get_location_token", description: "Get location-scoped access token", type: "tool" },
  // Contacts (23)
  { name: "crm_create_contact", description: "Create a new contact with fields", type: "tool" },
  { name: "crm_get_contact", description: "Retrieve contact by ID", type: "tool" },
  { name: "crm_update_contact", description: "Update contact fields", type: "tool" },
  { name: "crm_delete_contact", description: "Remove a contact permanently", type: "tool" },
  { name: "crm_search_contacts", description: "Search contacts by query", type: "tool" },
  { name: "crm_list_contacts", description: "List all contacts with pagination", type: "tool" },
  { name: "crm_add_contact_tag", description: "Add tags to a contact", type: "tool" },
  { name: "crm_remove_contact_tag", description: "Remove tags from a contact", type: "tool" },
  { name: "crm_add_contact_note", description: "Add a note to a contact", type: "tool" },
  { name: "crm_get_contact_notes", description: "List notes for a contact", type: "tool" },
  { name: "crm_add_contact_task", description: "Create a task for a contact", type: "tool" },
  { name: "crm_get_contact_tasks", description: "List tasks for a contact", type: "tool" },
  { name: "crm_add_contact_appointment", description: "Schedule appointment for contact", type: "tool" },
  { name: "crm_get_contact_appointments", description: "List appointments for a contact", type: "tool" },
  { name: "crm_add_contact_to_workflow", description: "Enroll contact in automation workflow", type: "tool" },
  { name: "crm_remove_contact_from_workflow", description: "Remove contact from workflow", type: "tool" },
  { name: "crm_get_contact_campaigns", description: "List campaigns for a contact", type: "tool" },
  { name: "crm_upsert_contact", description: "Create or update contact by email/phone", type: "tool" },
  { name: "crm_merge_contacts", description: "Merge duplicate contacts", type: "tool" },
  { name: "crm_get_contact_by_email", description: "Lookup contact by email address", type: "tool" },
  { name: "crm_get_contact_by_phone", description: "Lookup contact by phone number", type: "tool" },
  { name: "crm_bulk_update_contacts", description: "Update multiple contacts at once", type: "tool" },
  { name: "crm_contact_created", description: "Triggered when new contact is created", type: "trigger" },
  // Conversations (13)
  { name: "crm_list_conversations", description: "List all conversations", type: "tool" },
  { name: "crm_get_conversation", description: "Get conversation by ID", type: "tool" },
  { name: "crm_create_conversation", description: "Start a new conversation", type: "tool" },
  { name: "crm_send_message", description: "Send message in a conversation", type: "tool" },
  { name: "crm_get_messages", description: "List messages in a conversation", type: "tool" },
  { name: "crm_update_conversation", description: "Update conversation status", type: "tool" },
  { name: "crm_delete_conversation", description: "Delete a conversation", type: "tool" },
  { name: "crm_send_email", description: "Send email via conversation", type: "tool" },
  { name: "crm_send_sms", description: "Send SMS via conversation", type: "tool" },
  { name: "crm_get_email_history", description: "Get email thread history", type: "tool" },
  { name: "crm_schedule_message", description: "Schedule a future message", type: "tool" },
  { name: "crm_cancel_scheduled", description: "Cancel a scheduled message", type: "tool" },
  { name: "crm_message_received", description: "Triggered when message arrives", type: "trigger" },
  // Calendars (27)
  { name: "crm_list_calendars", description: "List all calendars", type: "tool" },
  { name: "crm_get_calendar", description: "Get calendar by ID", type: "tool" },
  { name: "crm_create_calendar", description: "Create a new calendar", type: "tool" },
  { name: "crm_update_calendar", description: "Update calendar settings", type: "tool" },
  { name: "crm_delete_calendar", description: "Delete a calendar", type: "tool" },
  { name: "crm_list_events", description: "List calendar events", type: "tool" },
  { name: "crm_get_event", description: "Get event by ID", type: "tool" },
  { name: "crm_create_event", description: "Create a calendar event", type: "tool" },
  { name: "crm_update_event", description: "Update an event", type: "tool" },
  { name: "crm_delete_event", description: "Delete an event", type: "tool" },
  { name: "crm_get_free_slots", description: "Get available booking slots", type: "tool" },
  { name: "crm_create_booking", description: "Create a booking/appointment", type: "tool" },
  { name: "crm_update_booking", description: "Update a booking", type: "tool" },
  { name: "crm_cancel_booking", description: "Cancel a booking", type: "tool" },
  { name: "crm_get_booking", description: "Get booking details", type: "tool" },
  { name: "crm_list_bookings", description: "List all bookings", type: "tool" },
  { name: "crm_create_calendar_group", description: "Create a calendar group", type: "tool" },
  { name: "crm_list_calendar_groups", description: "List calendar groups", type: "tool" },
  { name: "crm_update_calendar_group", description: "Update a calendar group", type: "tool" },
  { name: "crm_delete_calendar_group", description: "Delete a calendar group", type: "tool" },
  { name: "crm_get_calendar_resources", description: "List calendar resources", type: "tool" },
  { name: "crm_create_calendar_resource", description: "Create calendar resource", type: "tool" },
  { name: "crm_check_slot_availability", description: "Check specific slot availability", type: "tool" },
  { name: "crm_get_blocked_slots", description: "Get blocked time slots", type: "tool" },
  { name: "crm_block_slot", description: "Block a time slot", type: "tool" },
  { name: "crm_appointment_booked", description: "Triggered when appointment booked", type: "trigger" },
  { name: "crm_appointment_cancelled", description: "Triggered when appointment cancelled", type: "trigger" },
  // Opportunities (14)
  { name: "crm_list_pipelines", description: "List all sales pipelines", type: "tool" },
  { name: "crm_get_pipeline", description: "Get pipeline by ID", type: "tool" },
  { name: "crm_create_pipeline", description: "Create a new pipeline", type: "tool" },
  { name: "crm_list_opportunities", description: "List opportunities in pipeline", type: "tool" },
  { name: "crm_get_opportunity", description: "Get opportunity by ID", type: "tool" },
  { name: "crm_create_opportunity", description: "Create a new opportunity", type: "tool" },
  { name: "crm_update_opportunity", description: "Update opportunity fields/stage", type: "tool" },
  { name: "crm_delete_opportunity", description: "Delete an opportunity", type: "tool" },
  { name: "crm_update_opportunity_status", description: "Move opportunity to new stage", type: "tool" },
  { name: "crm_add_opportunity_follower", description: "Add follower to opportunity", type: "tool" },
  { name: "crm_remove_opportunity_follower", description: "Remove follower from opportunity", type: "tool" },
  { name: "crm_search_opportunities", description: "Search opportunities by query", type: "tool" },
  { name: "crm_opportunity_stage_changed", description: "Triggered when stage changes", type: "trigger" },
  { name: "crm_opportunity_created", description: "Triggered when opportunity created", type: "trigger" },
  // Invoices (20)
  { name: "crm_list_invoices", description: "List all invoices", type: "tool" },
  { name: "crm_get_invoice", description: "Get invoice by ID", type: "tool" },
  { name: "crm_create_invoice", description: "Create a new invoice", type: "tool" },
  { name: "crm_update_invoice", description: "Update invoice details", type: "tool" },
  { name: "crm_delete_invoice", description: "Delete an invoice", type: "tool" },
  { name: "crm_send_invoice", description: "Send invoice to customer", type: "tool" },
  { name: "crm_void_invoice", description: "Void an invoice", type: "tool" },
  { name: "crm_record_payment", description: "Record manual payment", type: "tool" },
  { name: "crm_list_invoice_items", description: "List items on an invoice", type: "tool" },
  { name: "crm_add_invoice_item", description: "Add item to invoice", type: "tool" },
  { name: "crm_update_invoice_item", description: "Update an invoice item", type: "tool" },
  { name: "crm_remove_invoice_item", description: "Remove item from invoice", type: "tool" },
  { name: "crm_generate_invoice_number", description: "Generate next invoice number", type: "tool" },
  { name: "crm_create_invoice_template", description: "Create invoice template", type: "tool" },
  { name: "crm_list_invoice_templates", description: "List invoice templates", type: "tool" },
  { name: "crm_get_invoice_schedule", description: "Get recurring schedule", type: "tool" },
  { name: "crm_create_invoice_schedule", description: "Create recurring invoice", type: "tool" },
  { name: "crm_update_invoice_schedule", description: "Update recurring schedule", type: "tool" },
  { name: "crm_invoice_paid", description: "Triggered when invoice is paid", type: "trigger" },
  { name: "crm_invoice_sent", description: "Triggered when invoice is sent", type: "trigger" },
  // Payments (16)
  { name: "crm_list_transactions", description: "List payment transactions", type: "tool" },
  { name: "crm_get_transaction", description: "Get transaction by ID", type: "tool" },
  { name: "crm_list_orders", description: "List all orders", type: "tool" },
  { name: "crm_get_order", description: "Get order by ID", type: "tool" },
  { name: "crm_create_order", description: "Create a new order", type: "tool" },
  { name: "crm_list_subscriptions", description: "List subscriptions", type: "tool" },
  { name: "crm_get_subscription", description: "Get subscription details", type: "tool" },
  { name: "crm_create_subscription", description: "Create a subscription", type: "tool" },
  { name: "crm_cancel_subscription", description: "Cancel a subscription", type: "tool" },
  { name: "crm_list_payment_methods", description: "List customer payment methods", type: "tool" },
  { name: "crm_charge_payment", description: "Process a one-time charge", type: "tool" },
  { name: "crm_refund_payment", description: "Issue a refund", type: "tool" },
  { name: "crm_get_payment_integration", description: "Get payment provider config", type: "tool" },
  { name: "crm_create_checkout_link", description: "Generate checkout link", type: "tool" },
  { name: "crm_payment_received", description: "Triggered when payment received", type: "trigger" },
  { name: "crm_subscription_cancelled", description: "Triggered on sub cancellation", type: "trigger" },
  // Products (10)
  { name: "crm_list_products", description: "List all products", type: "tool" },
  { name: "crm_get_product", description: "Get product by ID", type: "tool" },
  { name: "crm_create_product", description: "Create a new product", type: "tool" },
  { name: "crm_update_product", description: "Update product details", type: "tool" },
  { name: "crm_delete_product", description: "Delete a product", type: "tool" },
  { name: "crm_list_product_prices", description: "List prices for a product", type: "tool" },
  { name: "crm_create_product_price", description: "Create a product price", type: "tool" },
  { name: "crm_update_product_price", description: "Update a product price", type: "tool" },
  { name: "crm_delete_product_price", description: "Delete a product price", type: "tool" },
  { name: "crm_list_product_collections", description: "List product collections", type: "tool" },
  // Locations (24)
  { name: "crm_get_location", description: "Get location by ID", type: "tool" },
  { name: "crm_list_locations", description: "List all locations", type: "tool" },
  { name: "crm_update_location", description: "Update location settings", type: "tool" },
  { name: "crm_get_location_tags", description: "List location tags", type: "tool" },
  { name: "crm_create_location_tag", description: "Create a location tag", type: "tool" },
  { name: "crm_update_location_tag", description: "Update a location tag", type: "tool" },
  { name: "crm_delete_location_tag", description: "Delete a location tag", type: "tool" },
  { name: "crm_get_location_custom_fields", description: "List custom fields", type: "tool" },
  { name: "crm_create_location_custom_field", description: "Create custom field", type: "tool" },
  { name: "crm_update_location_custom_field", description: "Update custom field", type: "tool" },
  { name: "crm_delete_location_custom_field", description: "Delete custom field", type: "tool" },
  { name: "crm_get_location_custom_values", description: "Get custom field values", type: "tool" },
  { name: "crm_update_location_custom_values", description: "Update custom field values", type: "tool" },
  { name: "crm_list_location_templates", description: "List email/sms templates", type: "tool" },
  { name: "crm_get_location_snippets", description: "Get text snippets", type: "tool" },
  { name: "crm_create_location_snippet", description: "Create text snippet", type: "tool" },
  { name: "crm_list_location_pipelines", description: "List pipelines for location", type: "tool" },
  { name: "crm_get_location_tasks", description: "List tasks for location", type: "tool" },
  { name: "crm_search_location", description: "Search within location", type: "tool" },
  { name: "crm_get_location_timezone", description: "Get location timezone", type: "tool" },
  { name: "crm_update_location_timezone", description: "Update location timezone", type: "tool" },
  { name: "crm_get_location_business_info", description: "Get business information", type: "tool" },
  { name: "crm_update_location_business_info", description: "Update business information", type: "tool" },
  { name: "crm_get_location_integrations", description: "List connected integrations", type: "tool" },
  // Social (35)
  { name: "crm_list_social_accounts", description: "List connected social accounts", type: "tool" },
  { name: "crm_get_social_account", description: "Get social account details", type: "tool" },
  { name: "crm_connect_social_account", description: "Connect a social account", type: "tool" },
  { name: "crm_disconnect_social_account", description: "Disconnect social account", type: "tool" },
  { name: "crm_create_social_post", description: "Create a social media post", type: "tool" },
  { name: "crm_update_social_post", description: "Update a social post", type: "tool" },
  { name: "crm_delete_social_post", description: "Delete a social post", type: "tool" },
  { name: "crm_schedule_social_post", description: "Schedule future post", type: "tool" },
  { name: "crm_publish_social_post", description: "Publish post immediately", type: "tool" },
  { name: "crm_list_social_posts", description: "List all social posts", type: "tool" },
  { name: "crm_get_social_post", description: "Get post by ID", type: "tool" },
  { name: "crm_get_social_analytics", description: "Get post analytics", type: "tool" },
  { name: "crm_list_social_categories", description: "List post categories", type: "tool" },
  { name: "crm_create_social_category", description: "Create post category", type: "tool" },
  { name: "crm_list_social_tags", description: "List social tags", type: "tool" },
  { name: "crm_create_social_tag", description: "Create social tag", type: "tool" },
  { name: "crm_upload_social_media", description: "Upload media for posts", type: "tool" },
  { name: "crm_get_social_media", description: "Get uploaded media", type: "tool" },
  { name: "crm_delete_social_media", description: "Delete uploaded media", type: "tool" },
  { name: "crm_list_social_conversations", description: "List social conversations", type: "tool" },
  { name: "crm_reply_social_conversation", description: "Reply to social conversation", type: "tool" },
  { name: "crm_get_social_reviews", description: "Get Google/FB reviews", type: "tool" },
  { name: "crm_reply_social_review", description: "Reply to a review", type: "tool" },
  { name: "crm_get_social_insights", description: "Get audience insights", type: "tool" },
  { name: "crm_list_social_templates", description: "List post templates", type: "tool" },
  { name: "crm_create_social_template", description: "Create post template", type: "tool" },
  { name: "crm_get_social_calendar", description: "Get posting calendar", type: "tool" },
  { name: "crm_bulk_schedule_posts", description: "Schedule multiple posts", type: "tool" },
  { name: "crm_get_google_business", description: "Get Google Business profile", type: "tool" },
  { name: "crm_update_google_business", description: "Update Google Business", type: "tool" },
  { name: "crm_create_google_post", description: "Create Google Business post", type: "tool" },
  { name: "crm_get_facebook_insights", description: "Get Facebook page insights", type: "tool" },
  { name: "crm_get_instagram_insights", description: "Get Instagram insights", type: "tool" },
  { name: "crm_social_post_published", description: "Triggered on post publish", type: "trigger" },
  { name: "crm_social_review_received", description: "Triggered on new review", type: "trigger" },
  // Users (24)
  { name: "crm_list_users", description: "List all users", type: "tool" },
  { name: "crm_get_user", description: "Get user by ID", type: "tool" },
  { name: "crm_create_user", description: "Create a new user", type: "tool" },
  { name: "crm_update_user", description: "Update user details", type: "tool" },
  { name: "crm_delete_user", description: "Delete a user", type: "tool" },
  { name: "crm_get_user_permissions", description: "Get user permissions", type: "tool" },
  { name: "crm_update_user_permissions", description: "Update user permissions", type: "tool" },
  { name: "crm_list_user_roles", description: "List available roles", type: "tool" },
  { name: "crm_assign_user_role", description: "Assign role to user", type: "tool" },
  { name: "crm_remove_user_role", description: "Remove role from user", type: "tool" },
  { name: "crm_search_users", description: "Search users by query", type: "tool" },
  { name: "crm_get_user_availability", description: "Get user availability", type: "tool" },
  { name: "crm_update_user_availability", description: "Update user availability", type: "tool" },
  { name: "crm_get_user_calendars", description: "Get calendars for user", type: "tool" },
  { name: "crm_assign_user_calendar", description: "Assign calendar to user", type: "tool" },
  { name: "crm_get_user_teams", description: "Get user team memberships", type: "tool" },
  { name: "crm_create_team", description: "Create a team", type: "tool" },
  { name: "crm_list_teams", description: "List all teams", type: "tool" },
  { name: "crm_add_team_member", description: "Add user to team", type: "tool" },
  { name: "crm_remove_team_member", description: "Remove user from team", type: "tool" },
  { name: "crm_get_user_activity", description: "Get user activity log", type: "tool" },
  { name: "crm_invite_user", description: "Send user invitation", type: "tool" },
  { name: "crm_resend_invitation", description: "Resend user invitation", type: "tool" },
  { name: "crm_user_login", description: "Triggered on user login", type: "trigger" },
  // Objects (34)
  { name: "crm_list_custom_objects", description: "List custom object schemas", type: "tool" },
  { name: "crm_get_custom_object", description: "Get custom object schema", type: "tool" },
  { name: "crm_create_custom_object", description: "Create custom object schema", type: "tool" },
  { name: "crm_update_custom_object", description: "Update custom object schema", type: "tool" },
  { name: "crm_delete_custom_object", description: "Delete custom object schema", type: "tool" },
  { name: "crm_list_object_records", description: "List records for object", type: "tool" },
  { name: "crm_get_object_record", description: "Get specific record", type: "tool" },
  { name: "crm_create_object_record", description: "Create a new record", type: "tool" },
  { name: "crm_update_object_record", description: "Update a record", type: "tool" },
  { name: "crm_delete_object_record", description: "Delete a record", type: "tool" },
  { name: "crm_search_object_records", description: "Search records by query", type: "tool" },
  { name: "crm_list_object_fields", description: "List fields for object", type: "tool" },
  { name: "crm_create_object_field", description: "Create a field", type: "tool" },
  { name: "crm_update_object_field", description: "Update a field", type: "tool" },
  { name: "crm_delete_object_field", description: "Delete a field", type: "tool" },
  { name: "crm_list_object_relationships", description: "List object relationships", type: "tool" },
  { name: "crm_create_object_relationship", description: "Create relationship", type: "tool" },
  { name: "crm_delete_object_relationship", description: "Delete relationship", type: "tool" },
  { name: "crm_list_object_views", description: "List saved views", type: "tool" },
  { name: "crm_create_object_view", description: "Create a saved view", type: "tool" },
  { name: "crm_update_object_view", description: "Update a saved view", type: "tool" },
  { name: "crm_delete_object_view", description: "Delete a saved view", type: "tool" },
  { name: "crm_import_object_records", description: "Bulk import records", type: "tool" },
  { name: "crm_export_object_records", description: "Bulk export records", type: "tool" },
  { name: "crm_list_object_automations", description: "List automations for object", type: "tool" },
  { name: "crm_create_object_automation", description: "Create automation", type: "tool" },
  { name: "crm_list_object_webhooks", description: "List webhooks for object", type: "tool" },
  { name: "crm_create_object_webhook", description: "Create webhook", type: "tool" },
  { name: "crm_get_object_analytics", description: "Get object analytics", type: "tool" },
  { name: "crm_duplicate_object_record", description: "Duplicate a record", type: "tool" },
  { name: "crm_merge_object_records", description: "Merge duplicate records", type: "tool" },
  { name: "crm_bulk_update_records", description: "Bulk update records", type: "tool" },
  { name: "crm_object_record_created", description: "Triggered on record creation", type: "trigger" },
  { name: "crm_object_record_updated", description: "Triggered on record update", type: "trigger" },
]

// Catalog services tool data
export const TOOLS_BY_SERVICE: Record<string, Tool[]> = {
  stripe: [
    { name: "stripe_create_customer", description: "Create a Stripe customer", type: "tool" },
    { name: "stripe_list_customers", description: "List all Stripe customers", type: "tool" },
    { name: "stripe_get_customer", description: "Get customer by ID", type: "tool" },
    { name: "stripe_update_customer", description: "Update customer details", type: "tool" },
    { name: "stripe_create_payment_intent", description: "Create a payment intent", type: "tool" },
    { name: "stripe_create_checkout_session", description: "Create checkout session", type: "tool" },
    { name: "stripe_list_invoices", description: "List all invoices", type: "tool" },
    { name: "stripe_create_invoice", description: "Create a new invoice", type: "tool" },
    { name: "stripe_list_subscriptions", description: "List subscriptions", type: "tool" },
    { name: "stripe_create_subscription", description: "Create subscription", type: "tool" },
    { name: "stripe_cancel_subscription", description: "Cancel a subscription", type: "tool" },
    { name: "stripe_create_refund", description: "Issue a refund", type: "tool" },
    { name: "stripe_get_balance", description: "Get account balance", type: "tool" },
    { name: "stripe_create_product", description: "Create a product", type: "action" },
    { name: "stripe_create_price", description: "Create a price", type: "action" },
    { name: "stripe_create_coupon", description: "Create a coupon", type: "action" },
    { name: "stripe_payment_succeeded", description: "Payment intent succeeded", type: "trigger" },
    { name: "stripe_payment_failed", description: "Payment intent failed", type: "trigger" },
    { name: "stripe_invoice_paid", description: "Invoice was paid", type: "trigger" },
    { name: "stripe_subscription_created", description: "New subscription created", type: "trigger" },
    { name: "stripe_subscription_cancelled", description: "Subscription cancelled", type: "trigger" },
  ],
  sendgrid: [
    { name: "sendgrid_send_email", description: "Send a transactional email", type: "tool" },
    { name: "sendgrid_send_template_email", description: "Send email from template", type: "tool" },
    { name: "sendgrid_list_templates", description: "List email templates", type: "tool" },
    { name: "sendgrid_get_template", description: "Get template by ID", type: "tool" },
    { name: "sendgrid_list_contacts", description: "List marketing contacts", type: "tool" },
    { name: "sendgrid_add_contact", description: "Add marketing contact", type: "tool" },
    { name: "sendgrid_get_stats", description: "Get email statistics", type: "tool" },
    { name: "sendgrid_validate_email", description: "Validate an email address", type: "tool" },
    { name: "sendgrid_create_campaign", description: "Create email campaign", type: "action" },
    { name: "sendgrid_send_campaign", description: "Send email campaign", type: "action" },
    { name: "sendgrid_email_delivered", description: "Email was delivered", type: "trigger" },
    { name: "sendgrid_email_opened", description: "Email was opened", type: "trigger" },
    { name: "sendgrid_email_clicked", description: "Link was clicked", type: "trigger" },
    { name: "sendgrid_email_bounced", description: "Email bounced", type: "trigger" },
  ],
  resend: [
    { name: "resend_send_email", description: "Send an email via Resend", type: "tool" },
    { name: "resend_list_emails", description: "List sent emails", type: "tool" },
    { name: "resend_get_email", description: "Get email by ID", type: "tool" },
    { name: "resend_list_domains", description: "List verified domains", type: "tool" },
    { name: "resend_create_domain", description: "Add a domain", type: "tool" },
    { name: "resend_list_api_keys", description: "List API keys", type: "tool" },
    { name: "resend_create_batch", description: "Send batch emails", type: "action" },
    { name: "resend_create_audience", description: "Create email audience", type: "action" },
    { name: "resend_email_delivered", description: "Email delivered", type: "trigger" },
    { name: "resend_email_bounced", description: "Email bounced", type: "trigger" },
  ],
  gmail: [
    { name: "gmail_send_email", description: "Send email via Gmail", type: "tool" },
    { name: "gmail_list_messages", description: "List inbox messages", type: "tool" },
    { name: "gmail_get_message", description: "Get message by ID", type: "tool" },
    { name: "gmail_search_messages", description: "Search messages by query", type: "tool" },
    { name: "gmail_list_labels", description: "List Gmail labels", type: "tool" },
    { name: "gmail_create_draft", description: "Create email draft", type: "tool" },
    { name: "gmail_delete_message", description: "Delete a message", type: "tool" },
    { name: "gmail_modify_labels", description: "Add/remove message labels", type: "tool" },
    { name: "gmail_send_reply", description: "Reply to a thread", type: "action" },
    { name: "gmail_create_filter", description: "Create email filter", type: "action" },
    { name: "gmail_new_email", description: "New email received", type: "trigger" },
    { name: "gmail_label_applied", description: "Label was applied", type: "trigger" },
    { name: "gmail_attachment_received", description: "Attachment received", type: "trigger" },
  ],
  twilio: [
    { name: "twilio_send_sms", description: "Send an SMS message", type: "tool" },
    { name: "twilio_send_mms", description: "Send MMS with media", type: "tool" },
    { name: "twilio_list_messages", description: "List sent messages", type: "tool" },
    { name: "twilio_get_message", description: "Get message by SID", type: "tool" },
    { name: "twilio_make_call", description: "Initiate a phone call", type: "tool" },
    { name: "twilio_list_calls", description: "List call records", type: "tool" },
    { name: "twilio_send_whatsapp", description: "Send WhatsApp message", type: "tool" },
    { name: "twilio_lookup_phone", description: "Lookup phone number info", type: "tool" },
    { name: "twilio_create_flow", description: "Create Studio flow", type: "action" },
    { name: "twilio_buy_number", description: "Purchase phone number", type: "action" },
    { name: "twilio_sms_received", description: "SMS was received", type: "trigger" },
    { name: "twilio_call_completed", description: "Call completed", type: "trigger" },
    { name: "twilio_whatsapp_received", description: "WhatsApp received", type: "trigger" },
  ],
  slack: [
    { name: "slack_send_message", description: "Send message to channel", type: "tool" },
    { name: "slack_list_channels", description: "List workspace channels", type: "tool" },
    { name: "slack_get_channel", description: "Get channel info", type: "tool" },
    { name: "slack_create_channel", description: "Create a new channel", type: "tool" },
    { name: "slack_upload_file", description: "Upload a file", type: "tool" },
    { name: "slack_list_users", description: "List workspace members", type: "tool" },
    { name: "slack_send_dm", description: "Send direct message", type: "tool" },
    { name: "slack_add_reaction", description: "Add emoji reaction", type: "tool" },
    { name: "slack_set_topic", description: "Set channel topic", type: "tool" },
    { name: "slack_search_messages", description: "Search messages", type: "tool" },
    { name: "slack_post_blocks", description: "Send rich block message", type: "action" },
    { name: "slack_schedule_message", description: "Schedule a message", type: "action" },
    { name: "slack_message_posted", description: "New message in channel", type: "trigger" },
    { name: "slack_reaction_added", description: "Reaction added to message", type: "trigger" },
    { name: "slack_member_joined", description: "Member joined channel", type: "trigger" },
  ],
  discord: [
    { name: "discord_send_message", description: "Send message to channel", type: "tool" },
    { name: "discord_list_guilds", description: "List connected servers", type: "tool" },
    { name: "discord_list_channels", description: "List server channels", type: "tool" },
    { name: "discord_create_channel", description: "Create a channel", type: "tool" },
    { name: "discord_send_embed", description: "Send rich embed message", type: "tool" },
    { name: "discord_list_members", description: "List server members", type: "tool" },
    { name: "discord_assign_role", description: "Assign role to member", type: "tool" },
    { name: "discord_create_webhook", description: "Create a webhook", type: "tool" },
    { name: "discord_send_webhook", description: "Send via webhook", type: "tool" },
    { name: "discord_create_thread", description: "Create a thread", type: "tool" },
    { name: "discord_create_event", description: "Create server event", type: "action" },
    { name: "discord_create_poll", description: "Create a poll", type: "action" },
    { name: "discord_message_received", description: "New message in channel", type: "trigger" },
    { name: "discord_member_joined", description: "Member joined server", type: "trigger" },
  ],
  zoom: [
    { name: "zoom_create_meeting", description: "Create a Zoom meeting", type: "tool" },
    { name: "zoom_list_meetings", description: "List scheduled meetings", type: "tool" },
    { name: "zoom_get_meeting", description: "Get meeting details", type: "tool" },
    { name: "zoom_update_meeting", description: "Update meeting settings", type: "tool" },
    { name: "zoom_delete_meeting", description: "Delete a meeting", type: "tool" },
    { name: "zoom_list_recordings", description: "List meeting recordings", type: "tool" },
    { name: "zoom_get_user", description: "Get Zoom user info", type: "tool" },
    { name: "zoom_list_webinars", description: "List webinars", type: "tool" },
    { name: "zoom_create_webinar", description: "Create a webinar", type: "action" },
    { name: "zoom_add_registrant", description: "Add webinar registrant", type: "action" },
    { name: "zoom_meeting_started", description: "Meeting started", type: "trigger" },
    { name: "zoom_meeting_ended", description: "Meeting ended", type: "trigger" },
    { name: "zoom_participant_joined", description: "Participant joined", type: "trigger" },
  ],
  teams: [
    { name: "teams_send_message", description: "Send message to channel", type: "tool" },
    { name: "teams_list_teams", description: "List all teams", type: "tool" },
    { name: "teams_list_channels", description: "List team channels", type: "tool" },
    { name: "teams_create_channel", description: "Create a channel", type: "tool" },
    { name: "teams_list_members", description: "List team members", type: "tool" },
    { name: "teams_send_chat", description: "Send 1:1 chat message", type: "tool" },
    { name: "teams_create_meeting", description: "Create Teams meeting", type: "tool" },
    { name: "teams_upload_file", description: "Upload file to channel", type: "tool" },
    { name: "teams_create_tab", description: "Create channel tab", type: "action" },
    { name: "teams_create_plan", description: "Create Planner plan", type: "action" },
    { name: "teams_message_received", description: "New message in channel", type: "trigger" },
    { name: "teams_member_added", description: "Member added to team", type: "trigger" },
  ],
  openai: [
    { name: "openai_chat_completion", description: "Generate chat completion", type: "tool" },
    { name: "openai_create_image", description: "Generate image with DALL-E", type: "tool" },
    { name: "openai_create_embedding", description: "Generate text embeddings", type: "tool" },
    { name: "openai_transcribe_audio", description: "Transcribe audio with Whisper", type: "tool" },
    { name: "openai_translate_audio", description: "Translate audio to English", type: "tool" },
    { name: "openai_create_speech", description: "Generate speech from text", type: "tool" },
    { name: "openai_moderate_content", description: "Check content moderation", type: "tool" },
    { name: "openai_list_models", description: "List available models", type: "tool" },
    { name: "openai_edit_image", description: "Edit image with DALL-E", type: "tool" },
    { name: "openai_create_fine_tune", description: "Create fine-tuning job", type: "tool" },
    { name: "openai_create_assistant", description: "Create an assistant", type: "action" },
    { name: "openai_create_thread", description: "Create assistant thread", type: "action" },
    { name: "openai_run_assistant", description: "Run assistant on thread", type: "action" },
    { name: "openai_fine_tune_completed", description: "Fine-tune job completed", type: "trigger" },
    { name: "openai_run_completed", description: "Assistant run completed", type: "trigger" },
  ],
  airtable: [
    { name: "airtable_list_records", description: "List records in a table", type: "tool" },
    { name: "airtable_get_record", description: "Get record by ID", type: "tool" },
    { name: "airtable_create_record", description: "Create a new record", type: "tool" },
    { name: "airtable_update_record", description: "Update an existing record", type: "tool" },
    { name: "airtable_delete_record", description: "Delete a record", type: "tool" },
    { name: "airtable_list_tables", description: "List tables in a base", type: "tool" },
    { name: "airtable_list_bases", description: "List all bases", type: "tool" },
    { name: "airtable_search_records", description: "Search with formula", type: "tool" },
    { name: "airtable_bulk_create", description: "Create multiple records", type: "tool" },
    { name: "airtable_create_table", description: "Create a new table", type: "action" },
    { name: "airtable_create_field", description: "Add field to table", type: "action" },
    { name: "airtable_record_created", description: "New record created", type: "trigger" },
    { name: "airtable_record_updated", description: "Record was updated", type: "trigger" },
  ],
  notion: [
    { name: "notion_list_pages", description: "List pages in workspace", type: "tool" },
    { name: "notion_get_page", description: "Get page by ID", type: "tool" },
    { name: "notion_create_page", description: "Create a new page", type: "tool" },
    { name: "notion_update_page", description: "Update page properties", type: "tool" },
    { name: "notion_list_databases", description: "List databases", type: "tool" },
    { name: "notion_query_database", description: "Query database with filters", type: "tool" },
    { name: "notion_create_database", description: "Create a database", type: "tool" },
    { name: "notion_append_blocks", description: "Append content blocks", type: "tool" },
    { name: "notion_search", description: "Search across workspace", type: "tool" },
    { name: "notion_create_comment", description: "Create a comment", type: "action" },
    { name: "notion_archive_page", description: "Archive a page", type: "action" },
    { name: "notion_page_created", description: "New page created", type: "trigger" },
    { name: "notion_page_updated", description: "Page was updated", type: "trigger" },
    { name: "notion_database_updated", description: "Database updated", type: "trigger" },
  ],
  supabase: [
    { name: "supabase_query", description: "Run SQL query", type: "tool" },
    { name: "supabase_insert", description: "Insert rows into table", type: "tool" },
    { name: "supabase_update", description: "Update rows in table", type: "tool" },
    { name: "supabase_delete", description: "Delete rows from table", type: "tool" },
    { name: "supabase_list_tables", description: "List all tables", type: "tool" },
    { name: "supabase_rpc", description: "Call stored procedure", type: "tool" },
    { name: "supabase_storage_upload", description: "Upload file to storage", type: "tool" },
    { name: "supabase_storage_list", description: "List storage files", type: "tool" },
    { name: "supabase_auth_create_user", description: "Create auth user", type: "tool" },
    { name: "supabase_edge_invoke", description: "Invoke edge function", type: "tool" },
    { name: "supabase_create_table", description: "Create a new table", type: "action" },
    { name: "supabase_create_function", description: "Create edge function", type: "action" },
    { name: "supabase_row_inserted", description: "New row inserted", type: "trigger" },
    { name: "supabase_row_updated", description: "Row was updated", type: "trigger" },
    { name: "supabase_row_deleted", description: "Row was deleted", type: "trigger" },
    { name: "supabase_auth_event", description: "Auth event occurred", type: "trigger" },
  ],
  sheets: [
    { name: "sheets_read_range", description: "Read cell range", type: "tool" },
    { name: "sheets_write_range", description: "Write to cell range", type: "tool" },
    { name: "sheets_append_row", description: "Append row to sheet", type: "tool" },
    { name: "sheets_get_spreadsheet", description: "Get spreadsheet info", type: "tool" },
    { name: "sheets_list_sheets", description: "List sheets in workbook", type: "tool" },
    { name: "sheets_create_spreadsheet", description: "Create new spreadsheet", type: "tool" },
    { name: "sheets_clear_range", description: "Clear a cell range", type: "tool" },
    { name: "sheets_format_cells", description: "Format cell appearance", type: "tool" },
    { name: "sheets_create_sheet", description: "Create new sheet tab", type: "action" },
    { name: "sheets_add_chart", description: "Add chart to sheet", type: "action" },
    { name: "sheets_row_added", description: "New row added", type: "trigger" },
    { name: "sheets_cell_updated", description: "Cell value changed", type: "trigger" },
  ],
  mongodb: [
    { name: "mongodb_find", description: "Find documents by query", type: "tool" },
    { name: "mongodb_insert", description: "Insert document(s)", type: "tool" },
    { name: "mongodb_update", description: "Update document(s)", type: "tool" },
    { name: "mongodb_delete", description: "Delete document(s)", type: "tool" },
    { name: "mongodb_aggregate", description: "Run aggregation pipeline", type: "tool" },
    { name: "mongodb_list_collections", description: "List collections", type: "tool" },
    { name: "mongodb_count", description: "Count documents", type: "tool" },
    { name: "mongodb_create_index", description: "Create an index", type: "tool" },
    { name: "mongodb_create_collection", description: "Create collection", type: "action" },
    { name: "mongodb_bulk_write", description: "Bulk write operations", type: "action" },
    { name: "mongodb_document_inserted", description: "Document inserted", type: "trigger" },
    { name: "mongodb_document_updated", description: "Document updated", type: "trigger" },
  ],
  github: [
    { name: "github_list_repos", description: "List repositories", type: "tool" },
    { name: "github_get_repo", description: "Get repository details", type: "tool" },
    { name: "github_create_repo", description: "Create a repository", type: "tool" },
    { name: "github_list_issues", description: "List issues", type: "tool" },
    { name: "github_create_issue", description: "Create an issue", type: "tool" },
    { name: "github_list_prs", description: "List pull requests", type: "tool" },
    { name: "github_create_pr", description: "Create pull request", type: "tool" },
    { name: "github_merge_pr", description: "Merge pull request", type: "tool" },
    { name: "github_get_file", description: "Get file contents", type: "tool" },
    { name: "github_create_file", description: "Create/update file", type: "tool" },
    { name: "github_list_releases", description: "List releases", type: "tool" },
    { name: "github_list_workflows", description: "List Actions workflows", type: "tool" },
    { name: "github_trigger_workflow", description: "Trigger workflow run", type: "tool" },
    { name: "github_list_branches", description: "List branches", type: "tool" },
    { name: "github_create_release", description: "Create a release", type: "action" },
    { name: "github_dispatch_event", description: "Dispatch repository event", type: "action" },
    { name: "github_push", description: "Code was pushed", type: "trigger" },
    { name: "github_pr_opened", description: "PR was opened", type: "trigger" },
    { name: "github_issue_opened", description: "Issue was opened", type: "trigger" },
    { name: "github_release_published", description: "Release published", type: "trigger" },
    { name: "github_workflow_completed", description: "Workflow run completed", type: "trigger" },
    { name: "github_star_added", description: "Repository starred", type: "trigger" },
  ],
  linear: [
    { name: "linear_list_issues", description: "List issues", type: "tool" },
    { name: "linear_create_issue", description: "Create an issue", type: "tool" },
    { name: "linear_update_issue", description: "Update an issue", type: "tool" },
    { name: "linear_list_projects", description: "List projects", type: "tool" },
    { name: "linear_list_cycles", description: "List cycles", type: "tool" },
    { name: "linear_list_teams", description: "List teams", type: "tool" },
    { name: "linear_search_issues", description: "Search issues", type: "tool" },
    { name: "linear_get_issue", description: "Get issue details", type: "tool" },
    { name: "linear_create_project", description: "Create a project", type: "action" },
    { name: "linear_create_comment", description: "Add issue comment", type: "action" },
    { name: "linear_issue_created", description: "Issue created", type: "trigger" },
    { name: "linear_issue_updated", description: "Issue updated", type: "trigger" },
    { name: "linear_cycle_completed", description: "Cycle completed", type: "trigger" },
  ],
  jira: [
    { name: "jira_list_issues", description: "List/search issues via JQL", type: "tool" },
    { name: "jira_create_issue", description: "Create an issue", type: "tool" },
    { name: "jira_update_issue", description: "Update an issue", type: "tool" },
    { name: "jira_get_issue", description: "Get issue by key", type: "tool" },
    { name: "jira_list_projects", description: "List projects", type: "tool" },
    { name: "jira_list_sprints", description: "List sprints", type: "tool" },
    { name: "jira_transition_issue", description: "Change issue status", type: "tool" },
    { name: "jira_add_comment", description: "Add issue comment", type: "tool" },
    { name: "jira_create_sprint", description: "Create a sprint", type: "action" },
    { name: "jira_assign_issue", description: "Assign issue to user", type: "action" },
    { name: "jira_issue_created", description: "Issue created", type: "trigger" },
    { name: "jira_issue_updated", description: "Issue updated", type: "trigger" },
    { name: "jira_sprint_completed", description: "Sprint completed", type: "trigger" },
  ],
  shopify: [
    { name: "shopify_list_products", description: "List products", type: "tool" },
    { name: "shopify_get_product", description: "Get product by ID", type: "tool" },
    { name: "shopify_create_product", description: "Create a product", type: "tool" },
    { name: "shopify_update_product", description: "Update a product", type: "tool" },
    { name: "shopify_list_orders", description: "List orders", type: "tool" },
    { name: "shopify_get_order", description: "Get order by ID", type: "tool" },
    { name: "shopify_list_customers", description: "List customers", type: "tool" },
    { name: "shopify_update_inventory", description: "Update inventory level", type: "tool" },
    { name: "shopify_list_collections", description: "List collections", type: "tool" },
    { name: "shopify_create_discount", description: "Create discount code", type: "tool" },
    { name: "shopify_fulfill_order", description: "Fulfill an order", type: "tool" },
    { name: "shopify_cancel_order", description: "Cancel an order", type: "tool" },
    { name: "shopify_create_collection", description: "Create a collection", type: "action" },
    { name: "shopify_create_customer", description: "Create a customer", type: "action" },
    { name: "shopify_bulk_update", description: "Bulk update products", type: "action" },
    { name: "shopify_order_created", description: "New order placed", type: "trigger" },
    { name: "shopify_order_fulfilled", description: "Order fulfilled", type: "trigger" },
    { name: "shopify_product_created", description: "Product created", type: "trigger" },
    { name: "shopify_customer_created", description: "Customer created", type: "trigger" },
    { name: "shopify_inventory_updated", description: "Inventory changed", type: "trigger" },
  ],
  hubspot: [
    { name: "hubspot_list_contacts", description: "List contacts", type: "tool" },
    { name: "hubspot_create_contact", description: "Create a contact", type: "tool" },
    { name: "hubspot_update_contact", description: "Update a contact", type: "tool" },
    { name: "hubspot_list_deals", description: "List deals", type: "tool" },
    { name: "hubspot_create_deal", description: "Create a deal", type: "tool" },
    { name: "hubspot_update_deal", description: "Update a deal", type: "tool" },
    { name: "hubspot_list_companies", description: "List companies", type: "tool" },
    { name: "hubspot_create_company", description: "Create a company", type: "tool" },
    { name: "hubspot_search_crm", description: "Search CRM objects", type: "tool" },
    { name: "hubspot_list_pipelines", description: "List pipelines", type: "tool" },
    { name: "hubspot_create_engagement", description: "Create engagement", type: "tool" },
    { name: "hubspot_list_lists", description: "List contact lists", type: "tool" },
    { name: "hubspot_create_form", description: "Create a form", type: "action" },
    { name: "hubspot_create_campaign", description: "Create campaign", type: "action" },
    { name: "hubspot_send_email", description: "Send marketing email", type: "action" },
    { name: "hubspot_contact_created", description: "Contact created", type: "trigger" },
    { name: "hubspot_deal_created", description: "Deal created", type: "trigger" },
    { name: "hubspot_deal_stage_changed", description: "Deal stage changed", type: "trigger" },
    { name: "hubspot_form_submitted", description: "Form submitted", type: "trigger" },
  ],
  crm: CRM_TOOLS,
  calendly: [
    { name: "calendly_list_events", description: "List scheduled events", type: "tool" },
    { name: "calendly_get_event", description: "Get event details", type: "tool" },
    { name: "calendly_list_event_types", description: "List event types", type: "tool" },
    { name: "calendly_list_invitees", description: "List event invitees", type: "tool" },
    { name: "calendly_cancel_event", description: "Cancel an event", type: "tool" },
    { name: "calendly_get_user", description: "Get user availability", type: "tool" },
    { name: "calendly_create_webhook", description: "Create webhook", type: "action" },
    { name: "calendly_create_share_link", description: "Create shareable link", type: "action" },
    { name: "calendly_event_created", description: "Event was booked", type: "trigger" },
    { name: "calendly_event_cancelled", description: "Event cancelled", type: "trigger" },
    { name: "calendly_invitee_created", description: "Invitee added", type: "trigger" },
  ],
  gcal: [
    { name: "gcal_list_events", description: "List calendar events", type: "tool" },
    { name: "gcal_get_event", description: "Get event by ID", type: "tool" },
    { name: "gcal_create_event", description: "Create an event", type: "tool" },
    { name: "gcal_update_event", description: "Update an event", type: "tool" },
    { name: "gcal_delete_event", description: "Delete an event", type: "tool" },
    { name: "gcal_list_calendars", description: "List calendars", type: "tool" },
    { name: "gcal_free_busy", description: "Check free/busy times", type: "tool" },
    { name: "gcal_quick_add", description: "Quick add from text", type: "tool" },
    { name: "gcal_create_recurring", description: "Create recurring event", type: "action" },
    { name: "gcal_share_calendar", description: "Share calendar access", type: "action" },
    { name: "gcal_event_created", description: "Event was created", type: "trigger" },
    { name: "gcal_event_updated", description: "Event was updated", type: "trigger" },
    { name: "gcal_event_starting", description: "Event starting soon", type: "trigger" },
  ],
  gdrive: [
    { name: "gdrive_list_files", description: "List files and folders", type: "tool" },
    { name: "gdrive_get_file", description: "Get file metadata", type: "tool" },
    { name: "gdrive_upload_file", description: "Upload a file", type: "tool" },
    { name: "gdrive_download_file", description: "Download file content", type: "tool" },
    { name: "gdrive_create_folder", description: "Create a folder", type: "tool" },
    { name: "gdrive_search_files", description: "Search files by query", type: "tool" },
    { name: "gdrive_share_file", description: "Share file with users", type: "tool" },
    { name: "gdrive_move_file", description: "Move file to folder", type: "tool" },
    { name: "gdrive_copy_file", description: "Copy a file", type: "action" },
    { name: "gdrive_create_shortcut", description: "Create file shortcut", type: "action" },
    { name: "gdrive_file_created", description: "New file created", type: "trigger" },
    { name: "gdrive_file_modified", description: "File was modified", type: "trigger" },
  ],
  onedrive: [
    { name: "onedrive_list_files", description: "List files and folders", type: "tool" },
    { name: "onedrive_get_file", description: "Get file metadata", type: "tool" },
    { name: "onedrive_upload_file", description: "Upload a file", type: "tool" },
    { name: "onedrive_download_file", description: "Download a file", type: "tool" },
    { name: "onedrive_create_folder", description: "Create a folder", type: "tool" },
    { name: "onedrive_search_files", description: "Search files", type: "tool" },
    { name: "onedrive_share_file", description: "Share a file", type: "action" },
    { name: "onedrive_file_created", description: "New file created", type: "trigger" },
    { name: "onedrive_file_modified", description: "File was modified", type: "trigger" },
  ],
  zendesk: [
    { name: "zendesk_list_tickets", description: "List support tickets", type: "tool" },
    { name: "zendesk_get_ticket", description: "Get ticket by ID", type: "tool" },
    { name: "zendesk_create_ticket", description: "Create a ticket", type: "tool" },
    { name: "zendesk_update_ticket", description: "Update ticket status/fields", type: "tool" },
    { name: "zendesk_add_comment", description: "Add ticket comment", type: "tool" },
    { name: "zendesk_list_users", description: "List Zendesk users", type: "tool" },
    { name: "zendesk_search_tickets", description: "Search tickets", type: "tool" },
    { name: "zendesk_list_articles", description: "List knowledge base articles", type: "tool" },
    { name: "zendesk_create_article", description: "Create KB article", type: "action" },
    { name: "zendesk_assign_ticket", description: "Assign ticket to agent", type: "action" },
    { name: "zendesk_ticket_created", description: "New ticket created", type: "trigger" },
    { name: "zendesk_ticket_updated", description: "Ticket was updated", type: "trigger" },
    { name: "zendesk_ticket_solved", description: "Ticket was solved", type: "trigger" },
  ],
}

// Internal tools (Vault + Engine + Application)
export const INTERNAL_TOOLS: Tool[] = [
  // Vault (4)
  { name: "vault_seal", description: "Encrypt and store credentials with hardware binding", type: "tool" },
  { name: "vault_unseal", description: "Decrypt and retrieve stored credentials", type: "tool" },
  { name: "vault_verify", description: "Verify vault integrity and test credentials", type: "tool" },
  { name: "vault_fingerprint", description: "Get machine hardware fingerprint", type: "tool" },
  // Engine (6)
  { name: "engine_import", description: "Import credentials from .env, CSV, or JSON", type: "tool" },
  { name: "engine_verify", description: "Verify imported API keys against live services", type: "tool" },
  { name: "engine_platforms", description: "List supported AI platform targets", type: "tool" },
  { name: "engine_export", description: "Generate platform-specific configuration files", type: "tool" },
  { name: "engine_bundle", description: "Create portable encrypted .0n Brain bundle", type: "tool" },
  { name: "engine_open", description: "Open and decrypt a .0n Brain bundle", type: "tool" },
  // Application (5)
  { name: "app_create", description: "Create a new 0nMCP application", type: "tool" },
  { name: "app_list", description: "List all applications", type: "tool" },
  { name: "app_deploy", description: "Deploy application to target", type: "tool" },
  { name: "app_status", description: "Get application status", type: "tool" },
  { name: "app_logs", description: "Get application logs", type: "tool" },
]

export function getToolsForService(serviceId: string): Tool[] {
  return TOOLS_BY_SERVICE[serviceId] || []
}

export function getToolCount(serviceId: string): { tools: number; actions: number; triggers: number } {
  const tools = TOOLS_BY_SERVICE[serviceId] || []
  return {
    tools: tools.filter(t => t.type === "tool").length,
    actions: tools.filter(t => t.type === "action").length,
    triggers: tools.filter(t => t.type === "trigger").length,
  }
}
